import { useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { PlannerInput, Point } from '../types'
const W=560,H=310,PAD=28
function polygonArea(points:Point[]){let sum=0;for(let i=0;i<points.length;i++){const [x1,y1]=points[i],[x2,y2]=points[(i+1)%points.length];sum+=x1*y2-x2*y1}return Math.abs(sum)/2}
function orient(a:Point,b:Point,c:Point){return Math.sign((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))}
function intersect(a:Point,b:Point,c:Point,d:Point){return orient(a,b,c)!==orient(a,b,d)&&orient(c,d,a)!==orient(c,d,b)}
function selfIntersects(points:Point[]){for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){if(Math.abs(i-j)<=1||(i===0&&j===points.length-1))continue;if(intersect(points[i],points[(i+1)%points.length],points[j],points[(j+1)%points.length]))return true}return false}
function defaultPoints(shape:PlannerInput['plot']['shape'],l:number,w:number):Point[]{if(shape==='l_shape')return [[0,0],[l,0],[l,w*.52],[l*.52,w*.52],[l*.52,w],[0,w]];if(shape==='custom')return [[0,0],[l,0],[l,w*.72],[l*.65,w],[0,w]];return [[0,0],[l,0],[l,w],[0,w]]}
export default function PlotEditor({value,onChange}:{value:PlannerInput['plot'];onChange:(v:PlannerInput['plot'])=>void}){
 const{t}=useTranslation();const l=value.length_m||2,w=value.width_m||1.5;const points=value.shape==='custom'?(value.points||defaultPoints('custom',l,w)):defaultPoints(value.shape,l,w);const [history,setHistory]=useState<Point[][]>([]);const dragging=useRef<number|null>(null)
 const maxX=Math.max(...points.map(p=>p[0]),1),maxY=Math.max(...points.map(p=>p[1]),1),scale=Math.min((W-PAD*2)/maxX,(H-PAD*2)/maxY)
 const screen=(p:Point):Point=>[PAD+p[0]*scale,H-PAD-p[1]*scale]
 const invalid=useMemo(()=>selfIntersects(points),[points]);const area=polygonArea(points)
 function updatePoint(index:number,clientX:number,clientY:number,svg:SVGSVGElement){const rect=svg.getBoundingClientRect();const x=Math.max(0,Math.min(maxX,(clientX-rect.left)/rect.width*W-PAD))/scale;const y=Math.max(0,Math.min(maxY,(H-(clientY-rect.top)/rect.height*H-PAD)/scale));const next=points.map((p,i)=>i===index?[Number(x.toFixed(2)),Number(y.toFixed(2))] as Point:p);onChange({...value,points:next})}
 function setShape(shape:PlannerInput['plot']['shape']){const next={...value,shape,points:shape==='custom'?defaultPoints('custom',l,w):undefined};onChange(next)}
 return <div className="plot-editor"><div className="shape-tabs">{(['rectangle','square','l_shape','custom'] as const).map(s=><button key={s} className={value.shape===s?'active':''} onClick={()=>setShape(s)}>{t(s==='l_shape'?'lShape':s)}</button>)}</div><div className="dimension-row"><label>{t('length')}<span><input type="number" min="0.3" max="100" step="0.1" value={l} onChange={e=>onChange({...value,length_m:+e.target.value,points:value.shape==='custom'?value.points:undefined})}/>m</span></label><label>{t('width')}<span><input type="number" min="0.3" max="100" step="0.1" value={w} onChange={e=>onChange({...value,width_m:+e.target.value,points:value.shape==='custom'?value.points:undefined})}/>m</span></label><label>{t('sunDirection')}<select value={value.sun_direction} onChange={e=>onChange({...value,sun_direction:e.target.value as PlannerInput['plot']['sun_direction']})}>{(['north','east','south','west'] as const).map(x=><option key={x} value={x}>{t(x)}</option>)}</select></label></div><div className={`plot-canvas ${invalid?'invalid':''}`}><svg viewBox={`0 0 ${W} ${H}`} onPointerMove={e=>{if(dragging.current!==null&&value.shape==='custom')updatePoint(dragging.current,e.clientX,e.clientY,e.currentTarget)}} onPointerUp={()=>dragging.current=null} onPointerLeave={()=>dragging.current=null} role="img" aria-label="Plot shape editor"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M 28 0 L 0 0 0 28" fill="none" stroke="currentColor" strokeOpacity=".12"/></pattern></defs><rect width={W} height={H} fill="url(#grid)"/><polygon points={points.map(screen).map(p=>p.join(',')).join(' ')} className="plot-shape"/>{points.map((p,i)=>{const [cx,cy]=screen(p);return <circle key={i} cx={cx} cy={cy} r={value.shape==='custom'?10:5} className="plot-handle" onPointerDown={()=>{if(value.shape==='custom'){setHistory(h=>[...h.slice(-9),points]);dragging.current=i}}}/>})}<g className="sun-arrow" transform={`translate(${W-70} 42) rotate(${value.sun_direction==='north'?0:value.sun_direction==='east'?90:value.sun_direction==='south'?180:270})`}><path d="M0 22 V-10 M0-10 l-7 10 M0-10 l7 10"/><text x="10" y="6">☀</text></g></svg><div className="plot-area-badge"><small>{t('area')}</small><b>{area.toFixed(2)} m²</b></div></div>{invalid&&<p className="field-error">{t('polygonInvalid')}</p>}<div className="editor-actions">{value.shape==='custom'&&<button className="text-button" disabled={!history.length} onClick={()=>{const prior=history.at(-1);if(prior){onChange({...value,points:prior});setHistory(h=>h.slice(0,-1))}}}>{t('undo')}</button>}<button className="text-button" onClick={()=>onChange({...value,points:value.shape==='custom'?defaultPoints('custom',l,w):undefined})}>{t('reset')}</button></div></div>
}
export { selfIntersects, polygonArea }
